# Generated by Django 4.2.7 on 2025-10-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название скважины')),
                ('area', models.CharField(max_length=255, verbose_name='Участок')),
                ('structure', models.CharField(max_length=255, verbose_name='Сооружение')),
                ('design_depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Проектная глубина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wells',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Начало слоя')),
                ('end_depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Конец слоя')),
                ('lithology', models.CharField(choices=[('PRS', 'ПРС'), ('PEAT', 'Торф'), ('LOAM', 'Суглинок'), ('SANDY_LOAM', 'Супесь'), ('SAND', 'Песок')], max_length=20, verbose_name='Литология')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='drilling.well')),
            ],
            options={
                'db_table': 'layers',
                'ordering': ['start_depth'],
            },
        ),
    ]
